services:
  - type: web
    name: gisave-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      python -m flask db upgrade
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --worker-class sync --timeout 30 --max-requests 1000 --max-requests-jitter 50 wsgi:app
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: wsgi.py
      - key: PYTHONPATH
        value: .
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
    disk:
      name: uploads
      mountPath: /opt/render/project/src/instance/uploads
      sizeGB: 1
