version: '3.8'
services:
  web:
    build: .
    command: flask run --host=0.0.0.0 --port=5000
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///data.db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    ports:
      - '5000:5000'
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:7

  worker:
    build: .
    command: celery -A app.celery worker --loglevel=info
    environment:
      - FLASK_APP=app
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - .:/app
